name: ltcfarm-bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    strategy:
      fail-fast: false
      matrix:
        worker: [1,2,3,4,5]
        host: [1,2]

    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        run: |
          sudo apt update
          sudo apt install -y php-cli

      - name: Run bot
        run: php bot.php ${{ matrix.worker }} ${{ matrix.host }}
        env:
          CAPTCHA_APIKEY: ${{ secrets.CAPTCHA_APIKEY }}