name: ltcfarm-bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        run: python bot.py
